Changed indent to 4 spaces and fixed setup bug
Better compatibility with xcode and coda IDE's
Fixed bug in writing defaults (can't write in the source dir b/c plist
gets converted to binary after "defaults write") - also had wrong path
- $PWD instead of $HOME.
FInally, re-enabled the last_active check as it works as intended.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -59,6 +59,13 @@ usage ()
     exit 0
 }
 
+errtrap ()
+{   # Die if we trap an error
+    ES=${?}
+    printf "ERROR line ${1}: Command exited with status ${ES}.\n" |\
+    exit 1
+}
+
 # Main script
 while getopts ":urt:" OPTION; do
     case $OPTION in
@@ -69,6 +76,9 @@ while getopts ":urt:" OPTION; do
     esac
 done
 shift $((OPTIND-1))
+
+# trap errors
+trap 'errtrap ${LINENO}' ERR
 
 uninstall
 [[ $UNINSTALL == true ]] && exit 0
@@ -145,20 +155,22 @@ else
    printf "HOME_DOMAIN_PATTERN=\"$RESPONSE\"\n" >> $RC_FILE
 fi
 
+cp -r $(dirname $0)/Library ~/
+cat $(dirname $0)/Library/LaunchAgents/local.netwatcher.plist | sed "s/USERX/$USER/g" > ${HOME}/Library/LaunchAgents/local.netwatcher.plist
+
 if [[ $THROTTLE_SET == true ]]; then
    printf "Setting Throttle time to "$THROTTLE_TIME"\n"
-   defaults write "$PWD"/Library/LaunchAgents/local.netwatcher.plist \
+   defaults write ${HOME}/Library/LaunchAgents/local.netwatcher.plist \
             ProgramArguments \
-            -array "/Users/USERX/Library/Scripts/netwatcher" "-t $THROTTLE_TIME"
+            -array "${HOME}/Library/Scripts/netwatcher" "-t $THROTTLE_TIME"
 else
-   defaults write "$PWD"/Library/LaunchAgents/local.netwatcher.plist \
+   defaults write ${HOME}/Library/LaunchAgents/local.netwatcher.plist \
             ProgramArguments \
             -array "/Users/USERX/Library/Scripts/netwatcher" "-t 15"
 fi
 
-cp -r $(dirname $0)/Library ~/
-cat $(dirname $0)/Library/LaunchAgents/local.netwatcher.plist | sed "s/USERX/$USER/g" > ~/Library/LaunchAgents/local.netwatcher.plist
 launchctl load ~/Library/LaunchAgents/local.netwatcher.plist
+
 printf "Installation complete\n"
 printf "Use \"defaults read ~/Library/LaunchAgents/local.netwatcher.plist\" to see default plist values\n"
 printf "Use \"defaults write <key> <value> ~/Library/LaunchAgents/local.netwatcher.plist\" to change plist values\n"
